export type Lang = "en" | "es" | "zh" | "tl" | "fr";

export const pageTexts: Record<Lang, any> = {
  en: {
    contactPage: {
      title: "Contact Us",
      subtitle: "Get in touch with us for your outsourcing needs.",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      message: "Message",
      image: "Attach an Image (Optional)",
      acceptedImageFormats: "Accepted formats: JPG, PNG, GIF, WebP. Max file size: 5MB",
      submit: "Send Message",
      policyPrefix: "By submitting this form, you agree to our",
      privacyPolicy: "Privacy Policy",
    },
    learnMorePage: {
      title: "Learn More About Our Services",
      subtitle: "Discover how our outsourcing agency can help your business thrive.",
      clientManagementTitle: "Client Management",
      clientManagementDesc: "We handle all aspects of client relationships, from onboarding to ongoing support, ensuring your clients receive top-tier service.",
      projectTrackingTitle: "Project Tracking",
      projectTrackingDesc: "Our advanced project tracking systems keep you informed of progress, milestones, and deliverables in real-time.",
      employeeManagementTitle: "Employee Management",
      employeeManagementDesc: "We provide skilled employees tailored to your project needs, managing recruitment, training, and performance.",
    },
    clientManagementPage: {
      title: "Client Management Services",
      subtitle: "Let us handle your client relationships while you focus on your core business.",
      companyName: "Company Name",
      contactPerson: "Contact Person",
      email: "Email",
      requirements: "Client Management Requirements",
      requirementsPlaceholder: "Describe your client management needs...",
      submit: "Request Client Management Services",
    },
    projectTrackingPage: {
      title: "Project Tracking Services",
      subtitle: "Keep your projects on track with our comprehensive tracking solutions.",
      projectName: "Project Name",
      projectDescription: "Project Description",
      projectDescriptionPlaceholder: "Describe your project...",
      deadline: "Deadline",
      contactEmail: "Email ng Pakikipag-ugnayan",
      submit: "Start Project Tracking",
    },
    employeeManagementPage: {
      title: "Employee Management & Outsourcing",
      subtitle: "Access skilled professionals for your projects through our employee outsourcing services.",
      yourCompany: "Your Company",
      requiredPosition: "Required Position",
      requiredSkills: "Required Skills",
      requiredSkillsPlaceholder: "List the skills needed...",
      projectDuration: "Project Duration",
      projectDurationPlaceholder: "e.g., 3 months, 6 months",
      contactEmail: "Email ng Pakikipag-ugnayan",
      submit: "Request Employee Outsourcing",
    },
    statusPage: {
      title: "System Status",
      subtitle: "Stay updated with the latest system performance, updates, and announcements.",
      currentStatus: "Current Status",
      liveStatusMessage: "Live na Mensahe ng Katayuan",
      recentUpdates: "Recent Updates & Announcements",
      learnMore: "Learn More",
      close: "Close",
      updateTitle: "Website Changes Completed",
      updateDescription: "Changes have been made in the website.",
      updateDetails: "Changes have been made in the website on March 25, 2026.",
      updateDate: "March 25, 2026",
      liveMessage: "The website is currently up and running, but changes might happen as updates continue to roll out.",
      operational: "Operasyonal",
      operationalMessage: "All systems are currently running smoothly with no known issues.",
    },
  },
  es: {
    contactPage: {
      title: "Contáctanos",
      subtitle: "Ponte en contacto con nosotros para tus necesidades de subcontratación.",
      firstName: "Nombre",
      lastName: "Apellido",
      email: "Correo electrónico",
      message: "Mensaje",
      image: "Adjuntar una imagen (Opcional)",
      acceptedImageFormats: "Formatos aceptados: JPG, PNG, GIF, WebP. Tamaño máximo: 5MB",
      submit: "Enviar mensaje",
      policyPrefix: "Al enviar este formulario, aceptas nuestra",
      privacyPolicy: "Política de Privacidad",
    },
    learnMorePage: {
      title: "Conoce Más Sobre Nuestros Servicios",
      subtitle: "Descubre cómo nuestra agencia de outsourcing puede ayudar a tu negocio a crecer.",
      clientManagementTitle: "Gestión de Clientes",
      clientManagementDesc: "Gestionamos todos los aspectos de la relación con clientes, desde la incorporación hasta el soporte continuo.",
      projectTrackingTitle: "Seguimiento de Proyectos",
      projectTrackingDesc: "Nuestros sistemas avanzados de seguimiento te mantienen informado sobre progreso, hitos y entregables en tiempo real.",
      employeeManagementTitle: "Gestión de Empleados",
      employeeManagementDesc: "Proveemos personal calificado según las necesidades de tu proyecto, gestionando reclutamiento, capacitación y desempeño.",
    },
    clientManagementPage: {
      title: "Servicios de Gestión de Clientes",
      subtitle: "Déjanos gestionar tus relaciones con clientes mientras te enfocas en tu negocio principal.",
      companyName: "Nombre de la Empresa",
      contactPerson: "Persona de Contacto",
      email: "Correo electrónico",
      requirements: "Requisitos de Gestión de Clientes",
      requirementsPlaceholder: "Describe tus necesidades de gestión de clientes...",
      submit: "Solicitar Servicios de Gestión de Clientes",
    },
    projectTrackingPage: {
      title: "Servicios de Seguimiento de Proyectos",
      subtitle: "Mantén tus proyectos en curso con nuestras soluciones integrales de seguimiento.",
      projectName: "Nombre del Proyecto",
      projectDescription: "Descripción del Proyecto",
      projectDescriptionPlaceholder: "Describe tu proyecto...",
      deadline: "Fecha Límite",
      contactEmail: "Correo de Contacto",
      submit: "Iniciar Seguimiento de Proyecto",
    },
    employeeManagementPage: {
      title: "Gestión de Empleados y Outsourcing",
      subtitle: "Accede a profesionales calificados para tus proyectos mediante nuestros servicios de outsourcing.",
      yourCompany: "Tu Empresa",
      requiredPosition: "Puesto Requerido",
      requiredSkills: "Habilidades Requeridas",
      requiredSkillsPlaceholder: "Enumera las habilidades necesarias...",
      projectDuration: "Duración del Proyecto",
      projectDurationPlaceholder: "ej., 3 meses, 6 meses",
      contactEmail: "Correo de Contacto",
      submit: "Solicitar Outsourcing de Empleados",
    },
    statusPage: {
      title: "Estado del Sistema",
      subtitle: "Mantente al día con el rendimiento, actualizaciones y anuncios del sistema.",
      currentStatus: "Estado Actual",
      liveStatusMessage: "Mensaje de Estado en Vivo",
      recentUpdates: "Actualizaciones y Anuncios Recientes",
      learnMore: "Más información",
      close: "Cerrar",
      updateTitle: "Cambios del Sitio Completados",
      updateDescription: "Se realizaron cambios en el sitio web.",
      updateDetails: "Se realizaron cambios en el sitio web el 25 de marzo de 2026.",
      updateDate: "25 de marzo de 2026",
      liveMessage: "El sitio web está actualmente en funcionamiento, pero podrían ocurrir cambios mientras continúan las actualizaciones.",
      operational: "Operativo",
      operationalMessage: "Todos los sistemas funcionan correctamente y no hay problemas conocidos.",
    },
  },
  zh: {
    contactPage: {
      title: "联系我们",
      subtitle: "如有外包需求，请与我们联系。",
      firstName: "名字",
      lastName: "姓氏",
      email: "电子邮箱",
      message: "留言",
      image: "附加图像（可选）",
      acceptedImageFormats: "接受的格式：JPG、PNG、GIF、WebP。最大文件大小：5MB",
      submit: "发送消息",
      policyPrefix: "提交此表单即表示您同意我们的",
      privacyPolicy: "隐私政策",
    },
    learnMorePage: {
      title: "了解更多我们的服务",
      subtitle: "了解我们的外包机构如何帮助您的业务发展。",
      clientManagementTitle: "客户管理",
      clientManagementDesc: "我们负责客户关系的各个环节，从入驻到持续支持。",
      projectTrackingTitle: "项目跟踪",
      projectTrackingDesc: "我们的高级项目跟踪系统可让您实时了解进度、里程碑和交付情况。",
      employeeManagementTitle: "员工管理",
      employeeManagementDesc: "我们提供符合项目需求的专业人才，并管理招聘、培训和绩效。",
    },
    clientManagementPage: {
      title: "客户管理服务",
      subtitle: "让我们处理客户关系，您专注核心业务。",
      companyName: "公司名称",
      contactPerson: "联系人",
      email: "电子邮箱",
      requirements: "客户管理需求",
      requirementsPlaceholder: "请描述您的客户管理需求...",
      submit: "申请客户管理服务",
    },
    projectTrackingPage: {
      title: "项目跟踪服务",
      subtitle: "通过我们的全面跟踪方案让项目保持正轨。",
      projectName: "项目名称",
      projectDescription: "项目描述",
      projectDescriptionPlaceholder: "请描述您的项目...",
      deadline: "截止日期",
      contactEmail: "联系邮箱",
      submit: "开始项目跟踪",
    },
    employeeManagementPage: {
      title: "员工管理与外包",
      subtitle: "通过我们的员工外包服务获取项目所需专业人才。",
      yourCompany: "您的公司",
      requiredPosition: "所需岗位",
      requiredSkills: "所需技能",
      requiredSkillsPlaceholder: "请列出所需技能...",
      projectDuration: "项目时长",
      projectDurationPlaceholder: "例如：3个月、6个月",
      contactEmail: "联系邮箱",
      submit: "申请员工外包",
    },
    statusPage: {
      title: "系统状态",
      subtitle: "及时了解最新系统性能、更新和公告。",
      currentStatus: "当前状态",
      liveStatusMessage: "实时状态消息",
      recentUpdates: "最近更新与公告",
      learnMore: "了解更多",
      close: "关闭",
      updateTitle: "网站更改已完成",
      updateDescription: "网站已完成更改。",
      updateDetails: "网站更改已于 2026 年 3 月 25 日完成。",
      updateDate: "2026 年 3 月 25 日",
      liveMessage: "网站目前运行正常，但在更新持续发布期间可能会有变更。",
      operational: "正常运行",
      operationalMessage: "所有系统当前运行正常，暂无已知问题。",
    },
  },
  tl: {
    contactPage: {
      title: "Makipag-ugnayan",
      subtitle: "Makipag-ugnayan sa amin para sa iyong outsourcing needs.",
      firstName: "Pangalan",
      lastName: "Apelyido",
      email: "Email",
      message: "Mensahe",
      image: "Mag-attach ng Larawan (Opsyonal)",
      acceptedImageFormats: "Tinatanggap na formats: JPG, PNG, GIF, WebP. Max file size: 5MB",
      submit: "Ipadala ang Mensahe",
      policyPrefix: "Sa pagsusumite ng form na ito, sumasang-ayon ka sa aming",
      privacyPolicy: "Patakaran sa Privacy",
    },
    learnMorePage: {
      title: "Alamin Pa ang Aming Mga Serbisyo",
      subtitle: "Tuklasin kung paano makakatulong ang aming outsourcing agency sa iyong negosyo.",
      clientManagementTitle: "Pamamahala ng Kliyente",
      clientManagementDesc: "Pinamamahalaan namin ang lahat ng aspeto ng ugnayan sa kliyente, mula onboarding hanggang tuloy-tuloy na suporta.",
      projectTrackingTitle: "Pagsubaybay ng Proyekto",
      projectTrackingDesc: "Pinananatili kang updated ng aming advanced tracking systems sa progreso at milestones.",
      employeeManagementTitle: "Pamamahala ng Empleyado",
      employeeManagementDesc: "Nagbibigay kami ng mga skilled na empleyado ayon sa pangangailangan ng iyong proyekto.",
    },
    clientManagementPage: {
      title: "Mga Serbisyo sa Pamamahala ng Kliyente",
      subtitle: "Kami na ang bahala sa iyong client relationships habang nakatuon ka sa core business mo.",
      companyName: "Pangalan ng Kumpanya",
      contactPerson: "Contact Person",
      email: "Email",
      requirements: "Mga Kailangan sa Pamamahala ng Kliyente",
      requirementsPlaceholder: "Ilarawan ang iyong pangangailangan sa client management...",
      submit: "Humiling ng Serbisyo sa Client Management",
    },
    projectTrackingPage: {
      title: "Mga Serbisyo sa Pagsubaybay ng Proyekto",
      subtitle: "Panatilihing nasa tamang direksyon ang proyekto gamit ang aming tracking solutions.",
      projectName: "Pangalan ng Proyekto",
      projectDescription: "Paglalarawan ng Proyekto",
      projectDescriptionPlaceholder: "Ilarawan ang iyong proyekto...",
      deadline: "Deadline",
      contactEmail: "Contact Email",
      submit: "Simulan ang Project Tracking",
    },
    employeeManagementPage: {
      title: "Pamamahala ng Empleyado at Outsourcing",
      subtitle: "Kumuha ng skilled professionals para sa iyong proyekto sa pamamagitan ng aming services.",
      yourCompany: "Iyong Kumpanya",
      requiredPosition: "Kailangang Posisyon",
      requiredSkills: "Kailangang Kasanayan",
      requiredSkillsPlaceholder: "Ilista ang kinakailangang skills...",
      projectDuration: "Tagal ng Proyekto",
      projectDurationPlaceholder: "hal., 3 buwan, 6 buwan",
      contactEmail: "Contact Email",
      submit: "Humiling ng Employee Outsourcing",
    },
    statusPage: {
      title: "Katayuan ng Sistema",
      subtitle: "Manatiling updated sa pinakabagong performance, updates, at announcements.",
      currentStatus: "Kasalukuyang Katayuan",
      liveStatusMessage: "Live Status Message",
      recentUpdates: "Mga Kamakailang Update at Anunsyo",
      learnMore: "Alamin Pa",
      close: "Isara",
      updateTitle: "Natapos ang Mga Pagbabago sa Website",
      updateDescription: "May mga pagbabagong ginawa sa website.",
      updateDetails: "May mga pagbabagong ginawa sa website noong Marso 25, 2026.",
      updateDate: "Marso 25, 2026",
      liveMessage: "Kasalukuyang gumagana ang website, ngunit maaaring may mga pagbabago habang nagpapatuloy ang updates.",
      operational: "Operational",
      operationalMessage: "Maayos na tumatakbo ang lahat ng sistema at walang kilalang isyu.",
    },
  },
  fr: {
    contactPage: {
      title: "Contactez-nous",
      subtitle: "Contactez-nous pour vos besoins en externalisation.",
      firstName: "Prénom",
      lastName: "Nom",
      email: "E-mail",
      message: "Message",
       image: "Joindre une image (Facultatif)",
       acceptedImageFormats: "Formats acceptés : JPG, PNG, GIF, WebP. Taille max : 5MB",
       submit: "Envoyer le message",
      policyPrefix: "En soumettant ce formulaire, vous acceptez notre",
      privacyPolicy: "Politique de confidentialité",
    },
    learnMorePage: {
      title: "En savoir plus sur nos services",
      subtitle: "Découvrez comment notre agence d'externalisation peut aider votre entreprise à se développer.",
      clientManagementTitle: "Gestion des clients",
      clientManagementDesc: "Nous gérons tous les aspects de la relation client, de l'intégration au support continu.",
      projectTrackingTitle: "Suivi de projet",
      projectTrackingDesc: "Nos systèmes avancés vous informent en temps réel des progrès, jalons et livrables.",
      employeeManagementTitle: "Gestion des employés",
      employeeManagementDesc: "Nous fournissons des talents qualifiés adaptés à vos projets, avec recrutement et suivi.",
    },
    clientManagementPage: {
      title: "Services de gestion des clients",
      subtitle: "Laissez-nous gérer vos relations clients pendant que vous vous concentrez sur votre cœur de métier.",
      companyName: "Nom de l'entreprise",
      contactPerson: "Personne de contact",
      email: "E-mail",
      requirements: "Besoins en gestion client",
      requirementsPlaceholder: "Décrivez vos besoins en gestion client...",
      submit: "Demander des services de gestion client",
    },
    projectTrackingPage: {
      title: "Services de suivi de projet",
      subtitle: "Gardez vos projets sur la bonne voie grâce à nos solutions complètes.",
      projectName: "Nom du projet",
      projectDescription: "Description du projet",
      projectDescriptionPlaceholder: "Décrivez votre projet...",
      deadline: "Date limite",
      contactEmail: "E-mail de contact",
      submit: "Démarrer le suivi du projet",
    },
    employeeManagementPage: {
      title: "Gestion des employés et externalisation",
      subtitle: "Accédez à des professionnels qualifiés pour vos projets via nos services d'externalisation.",
      yourCompany: "Votre entreprise",
      requiredPosition: "Poste requis",
      requiredSkills: "Compétences requises",
      requiredSkillsPlaceholder: "Listez les compétences nécessaires...",
      projectDuration: "Durée du projet",
      projectDurationPlaceholder: "ex. : 3 mois, 6 mois",
      contactEmail: "E-mail de contact",
      submit: "Demander une externalisation de personnel",
    },
    statusPage: {
      title: "État du système",
      subtitle: "Restez informé des performances, mises à jour et annonces du système.",
      currentStatus: "État actuel",
      liveStatusMessage: "Message d'état en direct",
      recentUpdates: "Mises à jour et annonces récentes",
      learnMore: "En savoir plus",
      close: "Fermer",
      updateTitle: "Modifications du site terminées",
      updateDescription: "Des modifications ont été apportées au site web.",
      updateDetails: "Des modifications ont été apportées au site web le 25 mars 2026.",
      updateDate: "25 mars 2026",
      liveMessage: "Le site web est actuellement opérationnel, mais des changements peuvent survenir pendant le déploiement des mises à jour.",
      operational: "Opérationnel",
      operationalMessage: "Tous les systèmes fonctionnent correctement sans incident connu.",
    },
  },
};
